# MongoDB Veritabanına Bağlanma & Sorgulama

In [1]:
from pymongo import MongoClient
import pandas as pd

In [2]:
client = MongoClient("mongodb+srv://<username>:<password>@mycluster.3u0gdjt.mongodb.net/?retryWrites=true&w=majority")
client.test

Database(MongoClient(host=['ac-7h7obnn-shard-00-00.3u0gdjt.mongodb.net:27017', 'ac-7h7obnn-shard-00-02.3u0gdjt.mongodb.net:27017', 'ac-7h7obnn-shard-00-01.3u0gdjt.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-mfzh2e-shard-0', tls=True), 'test')

>**NOT:** `MongoClient` tanımlaması yaparken, MongoDB Atlas'dan aldığınız connection stringde `<username>` yazan yere tanımladığınız kullanıcı adını, `<password>` yazan yere ise belirlediğiniz parolayı girmeniz gerekiyor.

In [3]:
db = client.sample_training

In [4]:
db.list_collection_names()

['grades', 'zips', 'posts', 'companies', 'routes', 'trips', 'inspections']

In [5]:
collection = db.get_collection('trips')
collection

Collection(Database(MongoClient(host=['ac-7h7obnn-shard-00-00.3u0gdjt.mongodb.net:27017', 'ac-7h7obnn-shard-00-02.3u0gdjt.mongodb.net:27017', 'ac-7h7obnn-shard-00-01.3u0gdjt.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-mfzh2e-shard-0', tls=True), 'sample_training'), 'trips')

In [6]:
df = pd.DataFrame(list(collection.find()))
df

,_id,tripduration,start station id,start station name,end station id,end station name,bikeid,usertype,birth year,start station location,end station location,start time,stop time
0,572bb8222b288919b68abf5a,379,476,E 31 St & 3 Ave,498,Broadway & W 32 St,17827,Subscriber,1969,"{'type': 'Point', 'coordinates': [-73.97966069...","{'type': 'Point', 'coordinates': [-73.98808416...",2016-01-01 00:00:45,2016-01-01 00:07:04
1,572bb8222b288919b68abf5b,889,268,Howard St & Centre St,3002,South End Ave & Liberty St,22794,Subscriber,1961,"{'type': 'Point', 'coordinates': [-73.99973337...","{'type': 'Point', 'coordinates': [-74.015756, ...",2016-01-01 00:01:06,2016-01-01 00:15:56
2,572bb8222b288919b68abf5c,589,489,10 Ave & W 28 St,284,Greenwich Ave & 8 Ave,21997,Subscriber,1982,"{'type': 'Point', 'coordinates': [-74.00176802...","{'type': 'Point', 'coordinates': [-74.00263761...",2016-01-01 00:00:48,2016-01-01 00:10:37
3,572bb8222b288919b68abf5d,923,268,Howard St & Centre St,3002,South End Ave & Liberty St,22285,Subscriber,1958,"{'type': 'Point', 'coordinates': [-73.99973337...","{'type': 'Point', 'coordinates': [-74.015756, ...",2016-01-01 00:00:41,2016-01-01 00:16:04
4,572bb8222b288919b68abf5e,332,3104,Kent Ave & N 7 St,389,Broadway & Berry St,15788,Subscriber,1984,"{'type': 'Point', 'coordinates': [-73.96150225...","{'type': 'Point', 'coordinates': [-73.96525063...",2016-01-01 00:01:19,2016-01-01 00:06:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,572bb8232b288919b68b1c44,566,442,W 27 St & 7 Ave,380,W 4 St & 7 Ave S,15101,Subscriber,1988,"{'type': 'Point', 'coordinates': [-73.993915, ...","{'type': 'Point', 'coordinates': [-74.00293877...",2016-01-02 19:33:16,2016-01-02 19:42:42
9996,572bb8232b288919b68b1c48,552,438,St Marks Pl & 1 Ave,536,1 Ave & E 30 St,23575,Subscriber,1992,"{'type': 'Point', 'coordinates': [-73.98564945...","{'type': 'Point', 'coordinates': [-73.97536082...",2016-01-02 19:34:07,2016-01-02 19:43:19
9997,572bb8232b288919b68b1c4b,181,3142,1 Ave & E 62 St,385,E 55 St & 2 Ave,23998,Subscriber,1989,"{'type': 'Point', 'coordinates': [-73.96094022...","{'type': 'Point', 'coordinates': [-73.96603308...",2016-01-02 19:34:39,2016-01-02 19:37:41
9998,572bb8232b288919b68b1c4c,340,537,Lexington Ave & E 24 St,528,2 Ave & E 31 St,20767,Subscriber,1983,"{'type': 'Point', 'coordinates': [-73.98409214...","{'type': 'Point', 'coordinates': [-73.97706058...",2016-01-02 19:34:59,2016-01-02 19:40:40
9999,572bb8232b288919b68b1c50,2143,474,5 Ave & E 29 St,2021,W 45 St & 8 Ave,18057,Customer,,"{'type': 'Point', 'coordinates': [-73.98683077...","{'type': 'Point', 'coordinates': [-73.98859651...",2016-01-02 19:35:22,2016-01-02 20:11:06

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   _id                     10000 non-null  object
 1   tripduration            10000 non-null  int64
 2   start station id        10000 non-null  int64
 3   start station name      10000 non-null  object
 4   end station id          10000 non-null  int64
 5   end station name        10000 non-null  object
 6   bikeid                  10000 non-null  int64
 7   usertype                10000 non-null  object
 8   birth year              10000 non-null  object
 9   start station location  10000 non-null  object
 10  end station location    10000 non-null  object
 11  start time              10000 non-null  datetime64[ns]
 12  stop time               10000 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(4), object(7)
memory usage: 1015.8+ KB

In [8]:
pd.DataFrame(list(collection.find({"usertype":"Customer"})))

,_id,tripduration,start station id,start station name,end station id,end station name,bikeid,usertype,birth year,start station location,end station location,start time,stop time
0,572bb8222b288919b68abf6d,858,532,S 5 Pl & S 4 St,401,Allen St & Rivington St,17057,Customer,,"{'type': 'Point', 'coordinates': [-73.960876, ...","{'type': 'Point', 'coordinates': [-73.98997825...",2016-01-01 00:09:31,2016-01-01 00:23:49
1,572bb8222b288919b68abf6f,839,532,S 5 Pl & S 4 St,401,Allen St & Rivington St,17109,Customer,,"{'type': 'Point', 'coordinates': [-73.960876, ...","{'type': 'Point', 'coordinates': [-73.98997825...",2016-01-01 00:09:55,2016-01-01 00:23:54
2,572bb8222b288919b68abf70,110,439,E 4 St & 2 Ave,439,E 4 St & 2 Ave,24021,Customer,,"{'type': 'Point', 'coordinates': [-73.98978041...","{'type': 'Point', 'coordinates': [-73.98978041...",2016-01-01 00:10:24,2016-01-01 00:12:15
3,572bb8222b288919b68abf74,2023,3143,5 Ave & E 78 St,479,9 Ave & W 45 St,14769,Customer,,"{'type': 'Point', 'coordinates': [-73.96388769...","{'type': 'Point', 'coordinates': [-73.9912551,...",2016-01-01 00:11:15,2016-01-01 00:44:58
4,572bb8222b288919b68abf76,1236,3231,E 67 St & Park Ave,3231,E 67 St & Park Ave,16475,Customer,,"{'type': 'Point', 'coordinates': [-73.96592080...","{'type': 'Point', 'coordinates': [-73.96592080...",2016-01-01 00:12:14,2016-01-01 00:32:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1984,572bb8232b288919b68b1bf3,1121,532,S 5 Pl & S 4 St,401,Allen St & Rivington St,17750,Customer,,"{'type': 'Point', 'coordinates': [-73.960876, ...","{'type': 'Point', 'coordinates': [-73.98997825...",2016-01-02 19:26:12,2016-01-02 19:44:54
1985,572bb8232b288919b68b1c18,1543,285,Broadway & E 14 St,519,Pershing Square North,16867,Customer,,"{'type': 'Point', 'coordinates': [-73.99074142...","{'type': 'Point', 'coordinates': [-73.977706, ...",2016-01-02 19:29:22,2016-01-02 19:55:05
1986,572bb8232b288919b68b1c27,1319,3235,E 41 St & Madison Ave,490,8 Ave & W 33 St,24227,Customer,,"{'type': 'Point', 'coordinates': [-73.97992193...","{'type': 'Point', 'coordinates': [-73.993934, ...",2016-01-02 19:30:19,2016-01-02 19:52:19
1987,572bb8232b288919b68b1c40,3459,281,Grand Army Plaza & Central Park S,2006,Central Park S & 6 Ave,23657,Customer,,"{'type': 'Point', 'coordinates': [-73.97371465...","{'type': 'Point', 'coordinates': [-73.97634151...",2016-01-02 19:32:54,2016-01-02 20:30:33
1988,572bb8232b288919b68b1c50,2143,474,5 Ave & E 29 St,2021,W 45 St & 8 Ave,18057,Customer,,"{'type': 'Point', 'coordinates': [-73.98683077...","{'type': 'Point', 'coordinates': [-73.98859651...",2016-01-02 19:35:22,2016-01-02 20:11:06

>**NOT:** Collection tanımlamasını yaptıktan sonra `TAB`'e basarak kullanılabilecek tüm fonksiyonları görüntüleyebilirsiniz.